'use client';

import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, Bot, CheckCircle2, Clock3, Copy, FileText, LayoutDashboard, MessageSquare, RefreshCw, Send, Upload, Workflow } from 'lucide-react';

const nav = ['Dashboard', 'AI Chat', 'Cases', 'Workflows', 'Documents'];

type Case = { id:number; case_id:string; customer:string; issue:string; category:string; priority:string; status:string; summary:string; recommendation:string; email_draft:string; created_at:string };
type Dash = { total:number; high_priority:number; unresolved:number; resolved:number; categories:{name:string;count:number}[] };

export default function Home() {
  const [tab,setTab]=useState('Dashboard');
  const [dash,setDash]=useState<Dash>({total:0,high_priority:0,unresolved:0,resolved:0,categories:[]});
  const [cases,setCases]=useState<Case[]>([]);
  const [q,setQ]=useState(''); const [answer,setAnswer]=useState('');
  const [loading,setLoading]=useState(false); const [uploading,setUploading]=useState(false);
  const [dragActive,setDragActive]=useState(false); const [message,setMessage]=useState('');
  const documentInputRef=useRef<HTMLInputElement>(null);

  const refresh=async()=>{ try { const [d,c]=await Promise.all([fetch('/api/dashboard'),fetch('/api/cases')]); if(!d.ok||!c.ok) throw new Error(); setDash(await d.json()); setCases(await c.json()); } catch { setMessage('Could not reach the backend. Make sure FastAPI is running on port 8000.'); } };
  useEffect(()=>{refresh();},[]);

  const ask=async()=>{ if(!q.trim())return; setLoading(true); setAnswer(''); try { const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}); const x=await r.json(); setAnswer(r.ok?x.answer:`AI error: ${x.detail||'Request failed'}`); } catch { setAnswer('AI request failed.'); } finally { setLoading(false); } };

  const run=async()=>{ setLoading(true); setMessage(''); try { const r=await fetch('/api/workflow/run',{method:'POST'}); const x=await r.json(); setMessage(r.ok?x.message:`Workflow error: ${x.detail||'failed'}`); if(r.ok)await refresh(); } catch { setMessage('Workflow failed.'); } finally { setLoading(false); } };

  const uploadFile=async(file:File)=>{ if(!file)return; if(!/\.(csv|xlsx|xls|pdf)$/i.test(file.name)){setMessage('Please upload CSV, XLSX, XLS or PDF.');return;} setUploading(true);setMessage(''); try { const fd=new FormData();fd.append('file',file); const r=await fetch('/api/upload',{method:'POST',body:fd}); const x=await r.json(); setMessage(r.ok?x.message:`Upload failed: ${x.detail||'Unable to process file'}`); if(r.ok)await refresh(); } catch { setMessage('Upload failed. Make sure the backend is running.'); } finally { setUploading(false); } };
  const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)uploadFile(f);e.target.value='';};
  const handleDrop=(e:React.DragEvent<HTMLDivElement>)=>{e.preventDefault();e.stopPropagation();setDragActive(false);const f=e.dataTransfer.files?.[0];if(f)uploadFile(f);};

  return <main className="min-h-screen flex">
    <aside className="w-64 border-r border-slate-800 p-5 hidden md:block">
      <div className="flex items-center gap-3 mb-10"><div className="p-2 rounded-xl bg-indigo-500/20"><Bot size={24}/></div><div><b>OpsHub</b><div className="text-xs text-slate-500">AI Operations</div></div></div>
      {nav.map(n=><button key={n} onClick={()=>setTab(n)} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl mb-1 text-sm ${tab===n?'bg-slate-800 text-white':'text-slate-400 hover:bg-slate-900'}`}>{n==='Dashboard'?<LayoutDashboard size={17}/>:n==='AI Chat'?<MessageSquare size={17}/>:n==='Cases'?<FileText size={17}/>:n==='Workflows'?<Workflow size={17}/>:<FileText size={17}/>} {n}</button>)}
      <div className="mt-10 p-4 rounded-2xl bg-indigo-500/10 border border-indigo-400/10"><div className="text-xs text-indigo-300">AI STATUS</div><div className="flex gap-2 items-center mt-2 text-sm"><span className="w-2 h-2 rounded-full bg-emerald-400"/>Groq connected</div><div className="text-xs text-slate-500 mt-1">API key stays on backend</div></div>
    </aside>

    <section className="flex-1 p-5 md:p-8 max-w-7xl mx-auto w-full">
      <header className="flex justify-between items-center mb-8"><div><h1 className="text-2xl font-semibold">{tab}</h1><p className="text-slate-500 text-sm mt-1">Automate repetitive business operations with AI agents.</p></div><div className="flex gap-2"><label className="cursor-pointer px-4 py-2.5 rounded-xl bg-white text-slate-900 text-sm font-medium flex items-center gap-2">{uploading?<RefreshCw className="animate-spin" size={16}/>:<Upload size={16}/>} Upload data<input type="file" accept=".csv,.xlsx,.xls,.pdf" onChange={upload} className="hidden"/></label><button onClick={refresh} className="p-2.5 rounded-xl border border-slate-700"><RefreshCw size={18}/></button></div></header>
      {message&&<div className="mb-5 p-3 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-200 text-sm">{message}</div>}

      {tab==='Dashboard'&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[['Total Cases',dash.total,FileText],['High Priority',dash.high_priority,AlertTriangle],['Unresolved',dash.unresolved,Clock3],['Resolved',dash.resolved,CheckCircle2]].map(([a,v,I]:any)=><div className="card p-5" key={a}><div className="flex justify-between text-slate-500 text-sm"><span>{a}</span><I size={17}/></div><div className="text-3xl font-semibold mt-3">{v}</div></div>)}</div><div className="grid lg:grid-cols-3 gap-5"><div className="card p-5 lg:col-span-2"><div className="flex justify-between mb-5"><h2 className="font-semibold">AI Business Chat</h2><button onClick={()=>setTab('AI Chat')} className="text-xs text-indigo-300">Open full chat →</button></div><div className="rounded-2xl border border-slate-800 p-4 text-sm text-slate-400 mb-4">Ask questions about customers, priorities, trends or email drafts.</div><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Which customers have unresolved issues?" className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-4 py-3 outline-none"/><button onClick={ask} className="px-4 rounded-xl bg-indigo-500"><Send size={17}/></button></div>{answer&&<pre className="whitespace-pre-wrap mt-4 text-sm text-slate-300 bg-slate-950 rounded-xl p-4">{answer}</pre>}</div><div className="card p-5"><h2 className="font-semibold mb-5">Issue Categories</h2>{dash.categories.map(c=><div key={c.name} className="mb-4"><div className="flex justify-between text-sm mb-1"><span>{c.name}</span><span className="text-slate-500">{c.count}</span></div><div className="h-2 bg-slate-800 rounded-full"><div className="h-2 bg-indigo-400 rounded-full" style={{width:`${Math.min(100,c.count/Math.max(1,dash.total)*100*2.5)}%`}}/></div></div>)}</div></div><div className="card p-5 mt-5"><div className="flex justify-between mb-4"><h2 className="font-semibold">Recent Cases</h2><button onClick={()=>setTab('Cases')} className="text-xs text-indigo-300">View all →</button></div><CaseTable cases={cases.slice(0,6)}/></div></>}

      {tab==='AI Chat'&&<div className="card p-6 max-w-4xl"><h2 className="text-lg font-semibold mb-2">Ask your operations data</h2><p className="text-sm text-slate-500 mb-5">The assistant uses your uploaded case data.</p><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Summarize this month's cases" className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-4 py-3"/><button onClick={ask} className="px-5 rounded-xl bg-indigo-500"><Send size={17}/></button></div>{loading&&<p className="mt-5 text-sm text-slate-500">AI agent is analyzing…</p>}{answer&&<pre className="whitespace-pre-wrap mt-5 bg-slate-950 p-5 rounded-2xl text-sm leading-6">{answer}</pre>}<div className="grid md:grid-cols-2 gap-3 mt-6">{['Which customers have unresolved issues?','Show high-priority payment cases.','Summarize this month’s cases.','Draft an email for high-priority cases.'].map(x=><button onClick={()=>setQ(x)} key={x} className="text-left p-4 rounded-xl border border-slate-800 hover:bg-slate-900 text-sm">{x}</button>)}</div></div>}

      {tab==='Cases'&&<div className="card p-5"><CaseTable cases={cases}/></div>}

      {tab==='Workflows'&&<div className="card p-6 max-w-3xl"><div className="flex items-center gap-3 mb-3"><Workflow/><h2 className="text-lg font-semibold">Case Intelligence Workflow</h2></div><p className="text-slate-400 text-sm leading-6">Ingest → classify → prioritize → summarize → recommend → draft email. AI requests are batched to avoid rate-limit spikes.</p><div className="flex gap-3 my-7 flex-wrap">{['Ingest','Classify','Prioritize','Recommend','Draft Email','Store'].map((x,i)=><div className="px-4 py-3 rounded-xl bg-slate-900 border border-slate-800 text-sm" key={x}>{i+1}. {x}</div>)}</div><button disabled={loading||!cases.length} onClick={run} className="px-5 py-3 rounded-xl bg-indigo-500 font-medium disabled:opacity-50">{loading?'Running…':'Run workflow on all cases'}</button></div>}

      {tab==='Documents'&&<div className="card p-6"><h2 className="font-semibold mb-3">Document & Data Ingestion</h2><p className="text-sm text-slate-500">Upload CSV/XLSX for case analysis or PDF for document indexing.</p><div onClick={()=>documentInputRef.current?.click()} onDragEnter={e=>{e.preventDefault();setDragActive(true)}} onDragOver={e=>{e.preventDefault();setDragActive(true)}} onDragLeave={e=>{e.preventDefault();setDragActive(false)}} onDrop={handleDrop} className={`mt-6 flex flex-col items-center justify-center p-12 min-h-72 border-2 border-dashed rounded-2xl text-center cursor-pointer transition ${dragActive?'border-indigo-400 bg-indigo-500/10':'border-slate-700 hover:border-slate-500 hover:bg-slate-900/40'}`}>{uploading?<><RefreshCw className="mb-4 animate-spin text-indigo-400" size={32}/><div className="text-sm text-slate-300">Uploading...</div></>:<><Upload className={`mb-4 ${dragActive?'text-indigo-400':'text-slate-500'}`} size={32}/><div className="text-sm text-slate-300">{dragActive?'Drop your file here':'Drag & drop your file here'}</div><div className="text-xs text-slate-500 mt-2">or click to browse</div><div className="text-xs text-slate-600 mt-3">Supported: PDF, CSV, XLSX, XLS</div></>}<input ref={documentInputRef} type="file" accept=".csv,.xlsx,.xls,.pdf" onChange={upload} disabled={uploading} className="hidden"/></div></div>}
    </section>
  </main>;
}

function CaseTable({cases}:{cases:Case[]}){
  const [expanded,setExpanded]=useState<string|null>(null);
  const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text)}catch{}};
  if(!cases.length)return <div className="py-12 text-center text-slate-500">No cases yet. Upload a CSV/XLSX file from Documents.</div>;
  return <div className="space-y-3">{cases.map(c=>{const open=expanded===c.case_id;return <div key={c.case_id} className="rounded-2xl border border-slate-800 bg-slate-950/40 overflow-hidden"><button onClick={()=>setExpanded(open?null:c.case_id)} className="w-full text-left p-5 hover:bg-slate-900/60"><div className="grid grid-cols-1 md:grid-cols-6 gap-4 items-center"><div><div className="text-xs text-slate-500 mb-1">CASE</div><b>{c.case_id}</b></div><div><div className="text-xs text-slate-500 mb-1">CUSTOMER</div>{c.customer}</div><div><div className="text-xs text-slate-500 mb-1">CATEGORY</div>{c.category||'—'}</div><div><div className="text-xs text-slate-500 mb-1">PRIORITY</div><span className={`px-2.5 py-1 rounded-lg text-xs ${c.priority==='High'?'bg-red-500/10 text-red-300':c.priority==='Medium'?'bg-amber-500/10 text-amber-300':'bg-emerald-500/10 text-emerald-300'}`}>{c.priority||'—'}</span></div><div><div className="text-xs text-slate-500 mb-1">STATUS</div>{c.status}</div><div className="text-right text-indigo-300 text-sm">{open?'Hide details ↑':'View AI analysis →'}</div></div><div className="mt-4"><div className="text-xs text-slate-500 mb-1">ISSUE</div><div className="text-sm text-slate-300">{c.issue}</div></div></button>{open&&<div className="border-t border-slate-800 p-5 space-y-5"><Info title="AI Summary" value={c.summary||'No summary generated.'}/><Info title="Recommended Action" value={c.recommendation||'No recommendation generated.'}/><div><div className="flex items-center justify-between mb-2"><h3 className="font-semibold">AI-Generated Email Draft</h3><button onClick={()=>copy(c.email_draft||'')} className="px-3 py-1.5 rounded-lg border border-slate-700 text-xs flex items-center gap-1"><Copy size={13}/>Copy</button></div><pre className="whitespace-pre-wrap p-4 rounded-xl bg-slate-900 border border-slate-800 text-sm leading-6 text-slate-300">{c.email_draft||'No email draft generated.'}</pre></div></div>}</div>})}</div>;
}
function Info({title,value}:{title:string;value:string}){return <div><h3 className="font-semibold mb-2">{title}</h3><div className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-sm text-slate-300">{value}</div></div>}
